
GET http://localhost:3001/info/

###

GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/api/persons/64fe02aba6e576d328fd41c7

###

DELETE http://localhost:3001/api/persons/64fe85b1a145c8de7f98424e

###

DELETE http://localhost:3001/api/persons/invalidID

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "test",
    "number": "123-123"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "test2",
    "number": "123-123"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "test"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "number": "123-123"
}

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "123-123"
}
